### Question 1


In [2]:
import numpy as np

In [3]:
input_mat = np.matrix([[1,4,2,8],[3,4,5,1],[8,9,6,4],[3,8,2,6]])
con_mat = np.matrix([[1,0],[1,1]])


In [4]:
def conv(input_matrix,kernel,stride,pad):
    
    #Generating a new matrix which is input matrix padded with zeros
    input_height,input_width = input_matrix.shape
    pad_matrix = np.zeros((input_height+2*pad,input_width+2*pad),dtype=int)
    pad_matrix[pad : pad + input_height , pad : pad + input_width]= input_matrix
    
    
    #Determinig the size of output matrix
    output_height,output_width = tuple(map(lambda i,j : int(((i-j + 2*pad) //stride) + 1),input_matrix.shape,kernel.shape))
    output_matrix = np.zeros((output_height , output_width),dtype = int)

    
    #Kernel size. Kernel matrix would always be in square form.
    k = kernel.shape[0]
    
    
    
    #Perform dot product with the new pad_matrix and the kernel
    i_s = 0
    for i in range(output_height):
        j_s = 0
        for j in range(output_width):
            output_matrix[i,j] = np.sum(np.multiply(pad_matrix[i_s:i_s+k, j_s:j_s+k],kernel))
            j_s = j_s + stride   
        i_s = i_s + stride
    
    print(output_matrix)

### a

In [5]:
## 1
conv(input_mat,con_mat,1,0)

[[ 8 13  8]
 [20 19 15]
 [19 19 14]]


In [6]:
## 2
conv(input_mat,con_mat,2,2)

[[ 0  0  0  0]
 [ 0  8  8  0]
 [ 0 19 14  0]
 [ 0  0  0  0]]


### b

In [7]:
def conv_avg(input_matrix,kernel,stride,pad):
    
    #Generating a new matrix which is input matrix padded with zeros
    input_height,input_width = input_matrix.shape
    pad_matrix = np.zeros((input_height+2*pad,input_width+2*pad))
    pad_matrix[pad : pad + input_height , pad : pad + input_width]= input_matrix
    
    
    #Determinig the size of output matrix
    output_height,output_width = tuple(map(lambda i,j : int(((i-j + 2*pad) //stride) + 1),input_matrix.shape,kernel.shape))
    output_matrix = np.zeros((output_height , output_width))

    
    #Kernel size. Kernel matrix would always be in square form.
    k = kernel.shape[0]
    
    #Perform dot product with the new pad_matrix and the kernel
    i_s = 0
    for i in range(output_height):
        j_s = 0
        for j in range(output_width):
            output_matrix[i,j] = np.mean(np.multiply(pad_matrix[i_s:i_s+k, j_s:j_s+k],kernel))
            j_s = j_s + stride
        i_s = i_s + stride
    
    print(output_matrix)

In [8]:
kernel_unit = np.ones((3,3))
print(kernel_unit)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
input_mat_avg  = np.matrix([[1,4,2,7],[3,4,2,1],[3,9,6,4],[3,5,2,6]])

In [10]:
conv_avg(input_mat_avg,kernel_unit,1,0)

[[3.77777778 4.33333333]
 [4.11111111 4.33333333]]
